# Buildpacks to include in builder
[[buildpacks]]
uri = "buildpack"

# Order used for detection
[[order]]
    # This buildpack will display build-time information (as a dependency)
    [[order.group]]
    id = "esback"
    version = "0.0.1"

# Stack that will be used by the builder
[stack]
id = "io.buildpacks.esback.stacks.bionic"
# This image is used at runtime
run-image = "harbor-repo.vmware.com/esback/cnb-stack-runner:latest"
# This image is used at build-time
build-image = "harbor-repo.vmware.com/esback/cnb-stack-builder:latest"
