# This app-config file is used to configure the internally publish esback instance,
# used for acceptance testing. It is expected that this instance will be run with
# docker compose
app:
  title: Esback Test Instance
  baseUrl: ${BACKSTAGE_BASE_URL}

organization:
  name: VMware

backend:
  baseUrl: ${BACKSTAGE_BASE_URL}
  listen:
    port: 7007
    host: 0.0.0.0
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: ${BACKSTAGE_BASE_URL}
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'
  cache:
    store: memory

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

    - host: cmbu-githubent01.eng.vmware.com
      baseUrl: https://cmbu-githubent01.eng.vmware.com/
      apiBaseUrl: https://cmbu-githubent01.eng.vmware.com/api/v3
      token: ${GITHUB_ENTERPRISE_TOKEN}

  gitlab:
    - host: gitlab.eng.vmware.com
      baseUrl: https://gitlab.eng.vmware.com
      apiBaseUrl: https://gitlab.eng.vmware.com/api/v4/
      token: ${GITLAB_TOKEN}

  bitbucketServer:
    - host: ${BITBUCKET_HOST}
      apiBaseUrl: http://${BITBUCKET_HOST}/rest/api/1.0
      token: ${BITBUCKET_TOKEN}

catalog:
  providers:
    gitlab:
      esback:
        host: gitlab.eng.vmware.com
        group: esback
        entityFilename: packages/app/cypress/data/gitlab/catalog/components/gitlab-provider-component.yml
        schedule:
          frequency: { minutes: 1 }
          timeout: { minutes: 3 }
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    - type: file
      target: /app/examples/entities.yaml
    - type: file
      target: /app/examples/template/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: /app/examples/org.yaml
      rules:
        - allow: [User, Group]
    - type: url
      target: https://gitlab.eng.vmware.com/esback/core/-/blob/${GIT_BRANCH}/packages/app/cypress/data/gitlab/catalog/components/gitlab-integration-component.yml
    - type: url
      target: https://github.com/fouadh/foobar-backstage-component/blob/master/catalog-info.yaml
    - type: url
      target: https://cmbu-githubent01.eng.vmware.com/tap-gui/catalog/blob/main/catalog-info.yaml
    - type: url
      target: http://${BITBUCKET_HOST}/projects/ESBACK/repos/catalog/raw/catalog-info.yaml
    - type: system-x
      target: 'non empty string'
    - type: gitlab-discovery
      target: https://gitlab.eng.vmware.com/esback/blob/${GIT_BRANCH}/packages/app/cypress/data/gitlab/catalog/components/gitlab-processor-component.yml
