# This app-config file is used to configure the internally publish esback instance,
# used for acceptance testing. It is expected that this instance will be run with
# docker compose
app:
  title: Esback Test Instance
  baseUrl: ${BACKSTAGE_BASE_URL}

organization:
  name: VMware

backend:
  baseUrl: ${BACKSTAGE_BASE_URL}
  listen:
    port: 7007
    host: 0.0.0.0
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: ${BACKSTAGE_BASE_URL}
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'
  cache:
    store: memory

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

    - host: cmbu-githubent01.eng.vmware.com
      baseUrl: https://cmbu-githubent01.eng.vmware.com/
      apiBaseUrl: https://cmbu-githubent01.eng.vmware.com/api/v3
      token: ${GITHUB_ENTERPRISE_TOKEN}

  gitlab:
    - host: gitlab.eng.vmware.com
      baseUrl: https://gitlab.eng.vmware.com
      apiBaseUrl: https://gitlab.eng.vmware.com/api/v4/
      token: ${GITLAB_TOKEN}

  bitbucketServer:
    - host: ${BITBUCKET_HOST}
      apiBaseUrl: http://${BITBUCKET_HOST}/rest/api/1.0
      token: ${BITBUCKET_TOKEN}

catalog:
  providers:
    gitlab:
      esback:
        host: gitlab.eng.vmware.com
        group: esback
        entityFilename: packages/app/cypress/data/gitlab/catalog/components/gitlab-provider-component.yml
        schedule:
          frequency: { minutes: 1 }
          timeout: { minutes: 3 }
    github:
      esback:
        host: cmbu-githubent01.eng.vmware.com
        organization: 'esback'
        catalogPath: '/catalog-info.yaml'
        filters:
          branch: 'main'
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    - type: file
      target: /app/examples/entities.yaml
    - type: file
      target: /app/examples/template/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: /app/examples/org.yaml
      rules:
        - allow: [User, Group]
    - type: url
      target: https://gitlab.eng.vmware.com/esback/core/-/blob/${GIT_BRANCH}/packages/app/cypress/fixtures/gitlab/catalog/components/gitlab-integration-component.yml
    - type: url
      target: https://github.com/fouadh/foobar-backstage-component/blob/master/github-integration-component.yml
    - type: url
      target: https://cmbu-githubent01.eng.vmware.com/tap-gui/esback-e2e/blob/main/github-enterprise-integration-component.yml
    - type: system-x
      target: 'non empty string'
    - type: gitlab-discovery
      target: https://gitlab.eng.vmware.com/esback/blob/${GIT_BRANCH}/packages/app/cypress/fixtures/gitlab/catalog/components/gitlab-processor-component.yml

techdocs:
  builder: 'external' # Alternatives - 'external'
  generator:
    runIn: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.
    local:
      # (Optional). Set this to specify where the generated documentation is stored.
      publishDirectory: '/techdocs'

esback:
  catalog:
    providers:
      github:
        orgEntity:
          id: production
          orgUrl: 'https://cmbu-githubent01.eng.vmware.com/esback'
