# This app-config file is used to configure the internally publish esback instance,
# used for acceptance testing. It is expected that this instance will be run with
# docker compose
app:
  title: Esback Test Instance
  baseUrl: ${BACKSTAGE_BASE_URL}

organization:
  name: VMware

backend:
  baseUrl: ${BACKSTAGE_BASE_URL}
  listen:
    port: 7007
    host: 0.0.0.0
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: ${BACKSTAGE_BASE_URL}
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'
  cache:
    store: memory

integrations:
  gitlab:
    - host: gitlab.eng.vmware.com
      baseUrl: https://gitlab.eng.vmware.com
      apiBaseUrl: https://gitlab.eng.vmware.com/api/v4/
      token: ${GITLAB_TOKEN}

catalog:
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    - type: file
      target: /app/examples/entities.yaml
    - type: file
      target: /app/examples/template/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: /app/examples/org.yaml
      rules:
        - allow: [User, Group]
