app:
  title: Tanzu Developer Portal
  baseUrl: http://localhost:7007

organization:
  name: VMware

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
    host: 0.0.0.0
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    img-src: ["'self'", 'https:', 'data:']
    script-src: ["'self'", "'unsafe-eval'", "'unsafe-inline'", 'cdn.pendo.io']
    style-src: ["'self'", 'https:', "'unsafe-inline'"]
    upgrade-insecure-requests: false
  cors:
    origin: http://localhost:7007
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'
  cache:
    store: memory

catalog:
  rules:
    - allow:
        [
          Component,
          Domain,
          System,
          API,
          Group,
          User,
          Resource,
          Location,
          Template,
        ]
  locations: []

techdocs:
  builder: 'external'
