apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: esback
  description: An example of a Backstage application.
  annotations:
    gitlab.com/project-slug: esback/core
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
