#!/bin/ash

apk add --update python3 make g++ bash && rm -rf /var/cache/apk/*
apk update && apk add --no-cache build-base
cd ..
wget http://www.sqlite.org/sqlite-autoconf-3070603.tar.gz
tar xvfz sqlite-autoconf-3070603.tar.gz
cd sqlite-autoconf-3070603
./configure
make
make install
cd ../code