metadata:
  name: esback-test
  author: dbravo@vmware.com
  version: 0.0.1
plugins:
  app:
    - name: "@internal/plugin-esback-api-docs"
    - name: "@internal/plugin-esback-gitlab"
    - name: "@internal/plugin-esback-graphiql"
    - name: "@internal/plugin-esback-kubernetes"
    - name: "@internal/plugin-esback-scaffolder"
    - name: "@internal/plugin-esback-techdocs"
    - name: "@internal/plugin-esback-techradar"
  backend:
    - name: "@internal/plugin-esback-kubernetes-backend"
    - name: "@internal/plugin-esback-scaffolder-backend"
    - name: "@internal/plugin-esback-techdocs-backend"
