---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/vito/oci-build-task
inputs:
  - name: built-code
outputs:
  - name: image
params:
  CONTEXT: built-code/builder
  DOCKERFILE: built-code/builder/Dockerfile
run: { path: build }
