# To set up this pipeline, assuming you have an TPB target locally setup, run:
# $ fly -t esback set-pipeline -p mr-check -c ci/mr-check.yml -v initial_version=0.0.0
---
resource_types:
  - name: merge-request
    type: docker-image
    source:
      repository: harbor-repo.vmware.com/tmc_concourse_tools/gitlab-merge-request-resource
      tag: latest

resources:
  - name: version
    type: semver
    icon: counter
    source:
      driver: s3
      bucket: esback.ci
      key: build/esback/version/mrcheck
      initial_version: ((initial_version))
      access_key_id: ((aws.deprecated_access_key))
      secret_access_key: ((aws.deprecated_access_secret))
  - name: gitlab-mr
    type: merge-request
    icon: git
    source:
      uri: https://gitlab.eng.vmware.com/esback/core.git
      private_token: ((gitlab.core_token))
  - name: mr-image
    type: registry-image
    icon: docker
    source:
      repository: harbor-repo.vmware.com/esback/internal-instance
      username: ((harbor.username))
      password: ((harbor.token))
  # Integration tests tools
  - name: ytt
    type: github-release
    icon: github
    source:
      owner: vmware-tanzu
      repository: carvel-ytt
      access_token: ((github.access_token))
  - name: cypress-image
    type: registry-image
    icon: docker
    source:
      repository: harbor-repo.vmware.com/dockerhub-proxy-cache/cypress/included
      tag: 8.5.0
  - name: bitbucket-image
    type: registry-image
    icon: docker
    source:
      repository: harbor-repo.vmware.com/dockerhub-proxy-cache/atlassian/bitbucket
      tag: 8.4.2

on_failure_notification: &on_failure_notification
  put: gitlab-mr
  params:
    repository: gitlab-mr
    status: failed

jobs:
  - name: mark-mr-running
    public: true
    plan:
      - get: gitlab-mr
        trigger: true
        version: every
      - put: gitlab-mr
        params:
          repository: gitlab-mr
          status: running
    on_failure: *on_failure_notification
    on_error: *on_failure_notification
  - name: lint-and-test
    plan:
      - get: gitlab-mr
        passed: [mark-mr-running]
        trigger: true
      - in_parallel:
          - task: lint
            attempts: 2
            input_mapping:
              code: gitlab-mr
            file: gitlab-mr/ci/lint.yml
          - task: test
            attempts: 2
            input_mapping:
              code: gitlab-mr
            file: gitlab-mr/ci/unit-test.yml
    on_failure: *on_failure_notification
    on_error: *on_failure_notification
  - name: bump
    plan:
      - get: gitlab-mr
        passed: [lint-and-test]
        trigger: true
      - put: version
        params:
          pre: mrcheck
    on_failure: *on_failure_notification
    on_error: *on_failure_notification
  - name: build
    plan:
      - in_parallel:
          - do:
              - get: gitlab-mr
                passed: [bump]
                trigger: true
              - load_var: mrdata
                file: gitlab-mr/.git/merge-request.json
                reveal: true
          - do:
              - get: version
                passed: [bump]
                trigger: true
              - load_var: version
                file: version/version
                reveal: true
      - task: yarn-build
        input_mapping:
          code: gitlab-mr
        file: gitlab-mr/ci/yarn-build.yml
      - task: image-build
        privileged: true
        file: gitlab-mr/ci/image-build.yml
      - put: mr-image
        params:
          image: image/image.tar
          version: ((.:version))-((.:mrdata.source_branch))
    on_failure: *on_failure_notification
    on_error: *on_failure_notification
  - name: integration-tests
    plan:
      - in_parallel:
          - get: ytt
          - get: cypress-image
            params: { format: oci }
          - get: bitbucket-image
            params: { format: oci }
          - do:
              - get: gitlab-mr
                passed: [build]
                trigger: true
              - load_var: mrdata
                file: gitlab-mr/.git/merge-request.json
                reveal: true
          - get: mr-image
            params: { format: oci }
            passed: [build]
            trigger: true
      - task: test
        privileged: true
        file: gitlab-mr/ci/integration-tests.yml
        input_mapping:
          code: gitlab-mr
          docker-image: mr-image
        vars:
          auth0_client_id: ((auth0.svc_tpb_client_id))
          auth0_client_secret: ((auth0.svc_tpb_client_secret))
          auth0_domain: ((auth0.svc_tpb_domain))
          auth0_svc_tpb_refresh_token: ((e2e.auth0_svc_tpb_refresh_token))
          aws_access_key_id: ((e2e.aws_access_key_id))
          aws_secret_access_key: ((e2e.aws_secret_access_key))
          azure_token: ((e2e.azure_token))
          azure_tenant_id: ((e2e.azure_tenant_id))
          azure_client_id: ((e2e.azure_client_id))
          azure_client_secret: ((e2e.azure_client_secret))
          bitbucket_server_license: ((e2e.bitbucket_server_license))
          bitbucket_client_id: ((bitbucket.svc_tpb_client_id))
          bitbucket_client_secret: ((bitbucket.svc_tpb_client_secret))
          bitbucket_svc_tpb_refresh_token: ((e2e.bitbucket_svc_tpb_refresh_token))
          github_token: ((e2e.github_token))
          github_enterprise_token: ((e2e.github_enterprise_token))
          github_app_client_id: ((github.svc_tpb_client_id))
          github_app_client_secret: ((github.svc_tpb_client_secret))
          github_svc_tpb_refresh_token: ((e2e.github_svc_tpb_refresh_token))
          gitlab_token: ((gitlab.fixtures_token))
          gke_control_plane_endpoint: ((gke.control_plane_endpoint))
          gke_app_live_view_endpoint: ((gke.app_live_view_endpoint))
          gke_service_account_token: ((gke.service_account_token))
          gke_oidc_control_plane_endpoint: ((gke_oidc.control_plane_endpoint))
          gke_oidc_client_id: ((gke_oidc.svc_tpb_client_id))
          gke_oidc_client_secret: ((gke_oidc.svc_tpb_client_secret))
          google_svc_tpb_refresh_token: ((e2e.google_svc_tpb_refresh_token))
          okta_client_id: ((okta.svc_tpb_client_id))
          okta_client_secret: ((okta.svc_tpb_client_secret))
          okta_audience: ((okta.svc_tpb_audience))
          okta_svc_tpb_refresh_token: ((e2e.okta_svc_tpb_refresh_token))
    on_failure: *on_failure_notification
    on_error: *on_failure_notification
  - name: mark-mr-success
    public: true
    plan:
      - get: gitlab-mr
        passed: [lint-and-test, build, integration-tests]
        trigger: true
      - put: gitlab-mr
        params:
          repository: gitlab-mr
          status: success
    on_failure: *on_failure_notification
    on_error: *on_failure_notification
