# To set up this pipeline, assuming you have an esback target locally setup, run:
# $ fly -t esback set-pipeline -p core-runtime -c ci/pipeline.yml -v git_branch=$TARGET_BRANCH -v initial_version=0.0.0
---
resources:
  - name: version
    type: semver
    icon: counter
    source:
      driver: s3
      bucket: esback.ci
      key: build/esback/version/((git_branch))
      initial_version: ((initial_version))
      access_key_id: ((aws.deprecated_access_key))
      secret_access_key: ((aws.deprecated_access_secret))
  - name: esback-core
    type: git
    icon: gitlab
    source:
      uri: https://gitlab.eng.vmware.com/esback/core.git
      branch: ((git_branch))
      username: ((gitlab.username))
      password: ((gitlab.core_token))
  - name: core-image
    type: registry-image
    icon: docker
    source:
      repository: harbor-repo.vmware.com/esback/internal-instance
      username: ((harbor.username))
      password: ((harbor.token))
  - name: node-image
    type: registry-image
    icon: docker
    source:
      repository: harbor-repo.vmware.com/dockerhub-proxy-cache/library/node
      tag: 16-buster-slim
  - name: oci-build-task
    type: registry-image
    icon: docker
    source:
      repository: harbor-repo.vmware.com/dockerhub-proxy-cache/vito/oci-build-task
  # Integration tests tools
  - name: ytt
    type: github-release
    icon: github
    source:
      owner: vmware-tanzu
      repository: carvel-ytt
      access_token: ((github.access_token))
  - name: dcind-image
    type: registry-image
    icon: docker
    source:
      repository: harbor-repo.vmware.com/dockerhub-proxy-cache/amidos/dcind
      tag: 2.1.0
  - name: cypress-image
    type: registry-image
    icon: docker
    source:
      repository: harbor-repo.vmware.com/dockerhub-proxy-cache/cypress/included
      tag: 8.5.0

jobs:
  - name: reconfigure
    plan:
      - get: esback-core
        trigger: true
      - set_pipeline: core-runtime
        file: esback-core/ci/pipeline.yml
        vars:
          git_branch: ((git_branch))
          initial_version: ((initial_version))
  - name: lint-and-test
    plan:
      - get: code
        resource: esback-core
        passed: [reconfigure]
        trigger: true
      - get: node-image
      - in_parallel:
          - task: lint
            attempts: 3
            image: node-image
            config:
              platform: linux
              inputs:
                - name: code
              run:
                dir: code
                path: bash
                args:
                  - -exc
                  - |
                    yarn install --frozen-lockfile
                    yarn lint:all
                    yarn prettier:check
                    yarn tsc
          - task: test
            attempts: 3
            image: node-image
            config:
              platform: linux
              inputs:
                - name: code
              run:
                dir: code
                path: bash
                args:
                  - -exc
                  - |
                    yarn install --frozen-lockfile
                    CI=true yarn test:all
  - name: bump
    plan:
      - get: esback-core
        passed: [lint-and-test]
        trigger: true
      - put: version
        params:
          pre: ((git_branch))
  - name: build
    plan:
      - in_parallel:
          - get: esback-core
            passed: [bump]
            trigger: true
          - do:
              - get: version
                passed: [bump]
                trigger: true
              - load_var: version
                file: version/version
                reveal: true
          - get: node-image
          - get: oci-build-task
      - task: yarn-build
        image: node-image
        config:
          platform: linux
          inputs:
            - name: esback-core
          outputs:
            - name: built-code
              path: esback-core
          run:
            dir: esback-core
            path: bash
            args:
              - -exc
              - |
                yarn install --frozen-lockfile
                yarn tsc
                yarn build
      - task: image-build
        image: oci-build-task
        privileged: true
        config:
          platform: linux
          inputs:
            - name: built-code
          outputs:
            - name: image
          params:
            CONTEXT: built-code
            DOCKERFILE: built-code/packages/backend/Dockerfile
          run: { path: build }
      - put: core-image
        params:
          image: image/image.tar
          version: ((.:version))
  - name: integration-tests
    plan:
      - in_parallel:
          - get: dcind-image
          - get: ytt
          - get: cypress-image
            params: { format: oci }
          - get: esback-core
            passed: [build]
            trigger: true
          - get: core-image
            params: { format: oci }
            passed: [build]
            trigger: true
      - task: test
        privileged: true
        image: dcind-image
        config:
          platform: linux
          inputs:
            - name: ytt
            - name: cypress-image
            - name: esback-core
            - name: core-image
          params:
            DOCKER_CI_IMAGE: harbor-repo.vmware.com/esback/internal-instance
          run:
            dir: esback-core
            path: ci/scripts/integration_tests
