---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/library/alpine
outputs:
  - name: output
params:
  KUBECONFIG: ((kubeconfig))
run:
  path: sh
  args:
    - -exec
    - |
      echo "$KUBECONFIG" > output/config
