#!/usr/bin/env sh

set +e
. "$(dirname -- "$0")/_/husky.sh"

filesStaged=$(git diff --staged --name-only)

if echo $filesStaged | grep -E -i "packages/(app|backend)/src/core/plugins.ts"; then
	echo "Detected plugins added to the foundation. If this is not a mistake, use the --no-verify flag"
	exit 1
fi
