app:
  plugins:
    - name: '@tpb/plugin-hello-world'
    - name: '@tpb/plugin-rrv'
    - name: '@tpb/plugin-app-live-view'
    - name: '@tpb/plugin-azure-auth'
    - name: '@tpb/plugin-gitlab-auth'
    - name: '@tpb/plugin-google-auth'
    - name: '@tpb/plugin-auth0-auth'
    - name: '@tpb/plugin-okta-auth'
    - name: '@tpb/plugin-bitbucket-auth'
    - name: '@tpb/plugin-onelogin-auth'
    - name: '@tpb/plugin-oidc-auth'
    - name: '@tpb/plugin-github-auth'
    - name: '@tpb/plugin-guest-auth'
    - name: '@tpb/plugin-gitlab-loblaw'
      version: '^0.0.18'
backend:
  plugins:
    - name: '@tpb/plugin-catalog-test-entity-provider'
    - name: '@tpb/plugin-catalog-test-entity-processor'
    - name: '@tpb/plugin-gitlab-backend'
    - name: '@tpb/plugin-github-backend'
    - name: '@tpb/plugin-kubernetes-backend'
    - name: '@tpb/plugin-kubernetes-custom-apis-backend'
    - name: '@tpb/plugin-azure-auth-backend'
    - name: '@tpb/plugin-gitlab-auth-backend'
    - name: '@tpb/plugin-google-auth-backend'
    - name: '@tpb/plugin-auth0-auth-backend'
    - name: '@tpb/plugin-okta-auth-backend'
    - name: '@tpb/plugin-onelogin-auth-backend'
    - name: '@tpb/plugin-oidc-auth-backend'
    - name: '@tpb/plugin-github-auth-backend'
    - name: '@tpb/plugin-bitbucket-auth-backend'
    - name: '@tpb/plugin-azure-devops-backend'
    - name: '@tpb/plugin-ldap-backend'
    - name: '@tpb/plugin-ldap-test-transformers'
    - name: '@tpb/plugin-microsoft-graph-org-reader-processor'
    - name: '@tpb/plugin-microsoft-graph-org-reader-processor-test-transformers'
    - name: '@tpb/plugin-aws-s3-discovery-processor'
